replicaCount: 3

image:
  repository: shayma420/veterinairefrontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

env:
  - name: BACKEND_URL
    value: "http://veterinaire-service:3000"

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: veterinaire-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific

serviceAccount:
  create: true
  name: ""  # Use a default-generated name if left empty.

autoscaling:
  enabled: false  # Change to true if you want to enable HPA
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
