# Default values for veterinaire.
replicaCount: 3

image:
  repository: shayma420/veterinaire
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  - name: MONGO_URI
    value: "mongodb://mongodb:27017/veterinaire"
  - name: PORT
    value: "3000"

ingress:
  enabled: false

# Uncomment and set values as needed
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
