apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  BACKEND_URL: "http://veterinaire-service:3000"
  FRONTEND_URL: "http://veterinairefrontend-service:3001"
  MONGO_URI: "mongodb://root:password@mongo-service:27017/veterinaire?authSource=admin"
  DATABASE_NAME: "veterinaire"
