apiVersion: v1
kind: Service
metadata:
  name: veterinairefrontend-service
spec:
  selector:
    app: veterinaire-frontend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type : LoadBalancer