apiVersion: apps/v1
kind: Deployment
metadata:
  name: veterinairefrontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veterinaire-frontend
  template:
    metadata:
      labels:
        app: veterinaire-frontend
    spec:
      containers:
      - name: frontend
        image: shayma420/veterinairefrontend:latest
        ports:
        - containerPort: 3001
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_URL
